version: 2
jobs:
  init:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: # test what branch we're on.
        name: "Environment"
        command: echo ${CIRCLE_BRANCH}

      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Package Install
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: # test what branch we're on.
          name: "List directory"
          command: ls

  lint:
    docker:
      - image: node:10
    steps:
      - run:
          name: TSlint
          command: yarn tslint

      - run:
          name: Stylelint
          command: yarn stylelint
  test:
    docker:
      - image: node:10
    steps:
      - run:
          name: Test
          command: yarn test
  build:
    docker:
      - image: node:10
    steps:
      - run:
          name: Build
          command: yarn build
    branches:
      only:
        - production
        - staging

  deploy:
    docker:
      - image: node:10
    steps:
      - run:
          name: "Deploy to staging"
          command: ./node_modules/.bin/firebase deploy -P prodcution --token=$FIREBASE_TOKEN;
          branches:
            only: production

      - run:
          name: "Deploy to production"
          command: ./node_modules/.bin/firebase deploy -P staging --token=$FIREBASE_TOKEN;
          branches:
            only: staging
