version: 2
jobs:
  build:
    docker:
      - image: node:10

    steps:
      - checkout
      - run: # test what branch we're on.
          name: "Environment"
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: 
          name: Package Install
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: # test what branch we're on.
          name: "List directory"
          command: ls

      - run:
          name: TSlint
          command: yarn tslint

      - run:
          name: Stylelint
          command: yarn stylelint
      
      - run:
          name: Test
          command: yarn test

      - run:
          name: Build
          command: yarn build
#   deploy:
#     steps:
#       - run:
#           name: Firebase login
#           commnad: 
#       - run:
#           name: Deploy 
#           command:
